"""PER-CONSUMER characterization: does a marker that predates this PR still parse the same?

This PR repoints ``OPTIONS_RE_*`` onto one shared tempered body and head alternation,
and rewires SIX pre-existing consumers onto it — ``voice_reply``, Slack streaming and
Slack buffered, ``messaging/renderer``, ``preview_text``, ``whatsapp/turn_renderer``
and ``messaging/tables``. Each reads that machinery for a DIFFERENT purpose, so a
change that is right for one can be wrong for another, and a single aggregate
assertion cannot tell them apart.

That is not hypothetical. Repointing ``voice_reply`` onto the anchored LINE form once
made ``"See [OPTIONS: A | B] for details"`` — previously spoken as ``"See for
details"`` — start being READ ALOUD in full. A property test did not catch it and
neither did review; a per-consumer corpus did.

The expectations are CAPTURED, not authored: ``fixtures/marker_consumer_base_behaviour.json``
was generated by running this corpus through each consumer on a worktree at this
branch's base commit, with the PR absent. Any column that moves without an entry in
:data:`DELIBERATE_CHANGES` below is a regression in how an already-shipped marker
parses, and it fails here naming the consumer, the input and the old value.
"""

from __future__ import annotations

import hashlib
import json
import pathlib

import pytest

from kiro_crew import constants
from kiro_crew.messaging.renderer import split_options_trailer
from kiro_crew.messaging.tables import _table_run_end
from kiro_crew.preview_text import strip_markdown_preview
from kiro_crew.slack.format import extract_options
from kiro_crew.slack.handler import _filter_options_brackets, settle_marker_hold
from kiro_crew.voice_reply import strip_markdown
from kiro_crew.whatsapp.turn_renderer import _strip_options

FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "marker_consumer_base_behaviour.json"
BASE_BEHAVIOUR: dict[str, dict[str, object]] = json.loads(FIXTURE.read_text(encoding="utf-8"))

#: The changes this PR makes ON PURPOSE to a pre-existing marker's handling, each with
#: the reason. An entry here is a DECISION on record; anything not listed must not move.
DELIBERATE_CHANGES: dict[tuple[str, str], str] = {
    (
        "Markdown tic [OPTIONS: A | B](OPTIONS)",
        "slack.streaming.visible",
    ): (
        "streaming now agrees with BUFFERED, which already produced 'Markdown tic'. The "
        "two paths disagreeing about the same text was the defect, not the alignment."
    ),
    (
        "Unclosed [OPTIONS: A | B",
        "slack.streaming.visible",
    ): (
        "an UNTERMINATED head is withheld while streaming, because releasing it paints a "
        "half-written protocol tag into a bubble that cannot be edited. Buffered still "
        "shows it — it knows no more text is coming — and that divergence is deliberate."
    ),
    (
        "prose\n[options: lower | case]",
        "voice_reply.strip_markdown",
    ): (
        "speech strips a LOWERCASE head where the base read it aloud. `MARKER_STRIP_ANYWHERE_RE` "
        "is case-insensitive by design: a surface whose job is to remove protocol noise must "
        "not be case-sensitive. This widens CASING for SPEECH only — no marker becomes "
        "dispatchable, so the head-casing divergence the description declares is untouched."
    ),
    # SAME-LINE SIBLINGS. Base's body ran greedily to the line's LAST `]`, so a second
    # marker was swallowed into the first's final CHOICE LABEL. Every move below corrects that.
    (
        "Done.\n[OPTIONS: Alpha | Bravo] [OPTION-ACTIONS: close=Yes]",
        "renderer.split_options_trailer",
    ): (
        "the second choice was `'Bravo] [OPTION-ACTIONS: close=Yes'` — one label carrying a "
        "whole second marker, because the greedy body ran to the line's last `]`. The tempered "
        "body stops at the first, yielding `'Bravo'`. The base value was never a label a user "
        "could have meant."
    ),
    (
        "Done.\n[OPTIONS: Alpha | Bravo] [OPTION-ACTIONS: close=Yes]",
        "slack.extract_options.choices",
    ): (
        "same greedy-body correction as `renderer.split_options_trailer` on this input, in the "
        "surface that builds Slack's buttons: the base emitted a button labelled with the next "
        "marker's text."
    ),
    (
        "Done.\n[OPTIONS: Alpha | Bravo] [OPTION-ACTIONS: close=Yes]",
        "slack.streaming.visible",
    ): (
        "the base LEAKED `[OPTION-ACTIONS: close=Yes]` into the live bubble: having consumed "
        "the closing `]` as part of the first marker, it had no marker left to suppress and "
        "released the protocol text verbatim. Now both are consumed and neither is shown."
    ),
    (
        "Done.\n[OPTIONS: Alpha | Bravo] [OPTION-ACTIONS: close=Yes]",
        "voice_reply.strip_markdown",
    ): (
        "the base SPOKE ALOUD `[OPTION-ACTIONS: close=Yes]` for the same reason the streaming "
        "surface printed it. This is the exact failure mode the module docstring records for "
        '`"See [OPTIONS: A | B] for details"`, on a shape the corpus did not previously cover.'
    ),
}


def _measure(text: str) -> dict[str, object]:
    """Every consumer's answer for one input, in the fixture's own column names."""
    cleaned, choices = extract_options(text)
    # The streaming path is fed one character at a time, as the live bubble sees it.
    hold, buf = "", ""
    for char in text:
        hold, buf = _filter_options_brackets(char, hold, buf)
    return {
        "voice_reply.strip_markdown": strip_markdown(text),
        "slack.extract_options.cleaned": cleaned,
        "slack.extract_options.choices": choices,
        "preview_text.strip_markdown_preview": strip_markdown_preview(text),
        "whatsapp._strip_options": _strip_options(text),
        "renderer.split_options_trailer": list(split_options_trailer(text)),
        "tables._table_run_end": _table_run_end(text.split("\n"), 0),
        "slack.streaming.visible": buf + settle_marker_hold(hold),
    }


CONSUMERS = sorted(next(iter(BASE_BEHAVIOUR.values())).keys())


class TestEveryRewiredConsumerStillParsesPreExistingMarkers:
    def test_the_fixture_covers_every_rewired_consumer(self):
        """A column dropped from the fixture would silently stop being checked."""
        assert len(BASE_BEHAVIOUR) >= 13, "the corpus shrank"
        for expected in (
            "voice_reply.strip_markdown",
            "slack.extract_options.cleaned",
            "slack.streaming.visible",
            "renderer.split_options_trailer",
            "preview_text.strip_markdown_preview",
            "whatsapp._strip_options",
            "tables._table_run_end",
        ):
            assert expected in CONSUMERS, f"{expected} is no longer covered"

    @pytest.mark.parametrize("consumer", CONSUMERS)
    def test_consumer_matches_the_base_commit(self, consumer: str):
        """One test PER CONSUMER, so a failure names which surface moved."""
        drifted = []
        for text, base_row in BASE_BEHAVIOUR.items():
            now = _measure(text)[consumer]
            was = base_row[consumer]
            if isinstance(was, list):
                now = list(now)  # type: ignore[arg-type]
            if now == was:
                continue
            if (text, consumer) in DELIBERATE_CHANGES:
                continue
            drifted.append((text, was, now))
        assert not drifted, "\n".join(
            f"{consumer} changed for {t!r}: base {w!r} -> now {n!r}" for t, w, n in drifted
        )

    @pytest.mark.parametrize(("text", "consumer"), sorted(DELIBERATE_CHANGES))
    def test_each_declared_change_really_did_change(self, text: str, consumer: str):
        """The inverse ratchet: a stale exemption would hide a later regression.

        If one of these is ever made to match the base again, the entry must go —
        otherwise it sits in :data:`DELIBERATE_CHANGES` licensing a drift nobody
        intended.
        """
        assert _measure(text)[consumer] != BASE_BEHAVIOUR[text][consumer], (
            f"{consumer} now MATCHES the base for {text!r}, so its "
            "DELIBERATE_CHANGES entry is stale and must be deleted"
        )


#: Every behaviour-bearing value in the marker family, by name. Read RESOLVED, so a
#: comment reflow moves nothing while a semantic change does. See the ratchet below.
MARKER_FAMILY = (
    "MARKER_CLOSERS",
    "MARKER_OPENERS",
    "MARKER_PREFIXES",
    "_MARKER_HEADS",
    "_CASE_INSENSITIVE_MARKER_HEADS",
    "OPTIONS_RE_LINE",
    "OPTIONS_RE_TRAILER",
    "OPTION_ACTIONS_RE_LINE",
    "OPTION_ACTIONS_RE_TRAILER",
    "MARKER_STRIP_ANYWHERE_RE",
    "_MARKER_SUPPRESSION_HEAD_RE",
    "_MARKER_TRAILER_HEAD_SCAN_RE",
    "_MARKER_OPEN_SCAN_RE",
    "_MARKER_PREFIX_SCAN_RE",
    "_MARKER_HEAD_END_RE",
)

#: Recompute with the assertion below; it prints the value it measured.
MARKER_FAMILY_DIGEST = "ea46310e649ddf4f9a7c93c5c9d02f57874040435f0801aeccf6375707474dbd"


def _marker_family_digest() -> tuple[str, list[str]]:
    """Digest the family's resolved values, and return the lines that fed it."""
    lines: list[str] = []
    for name in MARKER_FAMILY:
        value = getattr(constants, name)
        pattern = getattr(value, "pattern", None)
        if pattern is None:
            lines.append(f"{name}={value!r}")
        else:
            lines.append(f"{name}=/{pattern}/{value.flags}")
    payload = "\n".join(lines)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest(), lines


def test_a_marker_family_edit_must_re_capture_the_corpus():
    """Make the characterization corpus MANDATORY for the marker family.

    The corpus pins consumer OUTPUTS for fixed INPUTS, so a family change that none of
    those inputs exercises passes it silently — which is how three behaviour changes
    reached review unannounced, one reading a marker aloud through TTS. This digest
    closes the gap from the other side: it fails on any semantic edit, whatever the
    inputs cover, so the corpus must be re-captured rather than merely still passing.

    Flags are digested too: ``re.IGNORECASE`` alone decides whether a lowercase head
    is a marker, and the pattern text does not show it.

    A tripwire, not a behaviour assertion. Clearing it is deliberate work: re-capture
    the consumer fixture against the new family, record every intended move in
    :data:`DELIBERATE_CHANGES` with its reason, then paste the digest printed here.
    """
    measured, lines = _marker_family_digest()
    assert measured == MARKER_FAMILY_DIGEST, (
        "constants.py's marker family changed.\n"
        f"  measured digest: {measured}\n"
        f"  pinned digest:   {MARKER_FAMILY_DIGEST}\n"
        "Re-capture the consumer corpus, declare each intended change in "
        "DELIBERATE_CHANGES, then update MARKER_FAMILY_DIGEST.\n"
        + "\n".join(f"  {line}" for line in lines)
    )


def test_the_digest_covers_every_family_member_it_names():
    """Positive control: a name that no longer exists must fail loudly, not silently.

    ``getattr`` on a renamed constant would raise, but a member quietly dropped from
    :data:`MARKER_FAMILY` would shrink the tripwire's coverage with every test still
    green — so assert the count as well as the digest.
    """
    _, lines = _marker_family_digest()
    assert len(lines) == len(MARKER_FAMILY)
    assert len(MARKER_FAMILY) == len(set(MARKER_FAMILY))
