"""Persistence for reports, analyses and human decisions.

Layout under the app's data dir (``~/.kiro/crew/workspace/pr-postmortem``)::

    reports/<fix_pr>.json              attribution report (mechanical)
    analysis/analysis-<fix_pr>.json    postmortem verdict (model, schema-checked)
    bundles/bundle-<fix_pr>.json       raw evidence the analysis was based on
    decisions.json                     human accept / reject -- the only file the UI writes
    state.json                         scan bookkeeping

Decisions live in their own file on purpose: the report files are regenerated by
every scan, and a human's accept must never be destroyed by a re-run.
"""

from __future__ import annotations

import json
import os
import tempfile
import threading
import time

from kiro_crew.apps.builtins.pr_postmortem.engine import analysis

# Matches app.json's `name`. ``is_app_enabled`` keys on it, so the two must agree
# or the enabled-gate would refuse every request for an app that is switched on.
APP_NAME = "pr-postmortem"

# Guards read-modify-write of decisions.json. The gateway serves requests on one
# event loop, but handlers can interleave around awaits, and the CLI writes too.
_LOCK = threading.Lock()

DECISIONS = ("accept", "reject", "defer")
LINK_DECISIONS = ("confirmed", "not_a_culprit")
# Lifecycle of a backlog cluster being turned into a real change.
APPLICATION_STATUSES = ("requested", "applied", "failed")


def data_dir() -> str:
    """Resolve the app's data directory.

    ``PRPM_DATA_DIR`` wins (tests, pods), then ``KIROCREW_HOME``, then the default.
    """
    override = os.environ.get("PRPM_DATA_DIR")
    if override:
        return override
    home = os.environ.get("KIROCREW_HOME") or os.path.join(
        os.path.expanduser("~"), ".kiro", "crew"
    )
    return os.path.join(home, "workspace", "pr-postmortem")


def _sub(name: str) -> str:
    path = os.path.join(data_dir(), name)
    os.makedirs(path, exist_ok=True)
    return path


def reports_dir() -> str:
    return _sub("reports")


def analysis_dir() -> str:
    return _sub("analysis")


def bundles_dir() -> str:
    return _sub("bundles")


def decisions_path() -> str:
    return os.path.join(data_dir(), "decisions.json")


def state_path() -> str:
    return os.path.join(data_dir(), "state.json")


def _read_json(path: str) -> dict | None:
    try:
        with open(path, encoding="utf-8") as fh:
            obj = json.load(fh)
        return obj if isinstance(obj, dict) else None
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def _write_json_atomic(path: str, obj: object) -> None:
    """Write via temp file + replace so a crash cannot truncate a decision file."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(obj, fh, indent=2)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# ── proposal identity ────────────────────────────────────────────────────────


def proposal_id(fix_pr: int, index: int) -> str:
    return f"{fix_pr}:{index}"


def parse_proposal_id(pid: str) -> tuple[int, int] | None:
    fix, _, idx = pid.partition(":")
    if not fix.isdigit() or not idx.isdigit():
        return None
    return int(fix), int(idx)


# ── decisions ────────────────────────────────────────────────────────────────


def retire_analysis(fix_pr: int) -> bool:
    """Move an invalidated analysis out of the active path. Returns True if moved.

    Called when re-attribution names a different culprit: every judgement in the
    analysis reasoned about the old pull request, so leaving it in place would keep
    its proposals acceptable -- and appliable -- against a PR they were never about.

    Renamed rather than deleted. The analysis cost a model call, and a human may
    want to compare what the tool believed before the culprit moved; the retired
    copy sits beside it as ``analysis-<pr>.retired-<n>.json`` and nothing reads it.
    """
    live = os.path.join(analysis_dir(), f"analysis-{fix_pr}.json")
    if not os.path.exists(live):
        return False
    for n in range(1, 100):
        dest = os.path.join(analysis_dir(), f"analysis-{fix_pr}.retired-{n}.json")
        if not os.path.exists(dest):
            os.replace(live, dest)
            return True
    # 99 retirements for one pair means something is looping; drop the file rather
    # than growing the directory without bound.
    os.remove(live)
    return True


def clear_decisions_for(fix_pr: int) -> int:
    """Drop every decision recorded for one fix PR. Returns how many were removed.

    Used before a forced re-analysis: proposal ids are positional
    (``<fix_pr>:<index>``), so keeping decisions across a rewritten proposal list
    would move a human's accept onto a different proposal.
    """
    dec = load_decisions()
    props = dec.get("proposals") or {}
    prefix = f"{fix_pr}:"
    doomed = [key for key in props if key.startswith(prefix)]
    for key in doomed:
        props.pop(key, None)
    if doomed:
        dec["proposals"] = props
        _write_json_atomic(decisions_path(), dec)
    return len(doomed)


def load_decisions() -> dict:
    obj = _read_json(decisions_path()) or {}
    obj.setdefault("proposals", {})
    obj.setdefault("links", {})
    obj.setdefault("applications", {})
    return obj


def set_application(
    cluster_id: str, status: str, target: str = "", note: str = "", url: str = ""
) -> dict:
    """Record that an accepted backlog cluster is being (or has been) applied.

    Lives with the decisions rather than the reports for the same reason: a scan
    rewrites reports, and losing the record would re-offer work already done.
    """
    if status not in APPLICATION_STATUSES:
        raise ValueError(f"status must be one of {APPLICATION_STATUSES}")
    if not cluster_id or not str(cluster_id).isalnum():
        raise ValueError("cluster id must be alphanumeric")
    with _LOCK:
        data = load_decisions()
        prev = data["applications"].get(cluster_id) or {}

        # A finished record is not overwritten by a fresh request. The page posts
        # `requested` as soon as it hands the plan to an agent, so clicking Apply
        # again on a cluster that had already completed replaced `applied` -- URL,
        # timestamp and all -- with a pending state, losing the only evidence that
        # the work had ever landed. `applied` is terminal; anything else may still
        # move. Same rule as save_attribution's: a re-run must not lose a result.
        # Found by review on PR #2354.
        if prev.get("status") == "applied" and status == "requested":
            return prev

        data["applications"][cluster_id] = {
            "status": status,
            "target": target or prev.get("target", ""),
            "note": note[:2000] or prev.get("note", ""),
            "url": url or prev.get("url", ""),
            "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }
        _write_json_atomic(decisions_path(), data)
        return data["applications"][cluster_id]


def load_applications() -> dict:
    return load_decisions()["applications"]


def set_proposal_decision(pid: str, decision: str, note: str = "") -> dict:
    if decision not in DECISIONS:
        raise ValueError(f"decision must be one of {DECISIONS}")
    if parse_proposal_id(pid) is None:
        raise ValueError("malformed proposal id")
    with _LOCK:
        data = load_decisions()
        data["proposals"][pid] = {
            "decision": decision,
            "note": note[:2000],
            "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }
        _write_json_atomic(decisions_path(), data)
        return data["proposals"][pid]


def set_link_decision(fix_pr: int, decision: str, note: str = "") -> dict:
    """Record a human ruling on whether the attribution itself is right.

    ``not_a_culprit`` is the correction path for a bad blame link -- the single
    most important human input, since a wrong culprit yields a wrong rule.
    """
    if decision not in LINK_DECISIONS:
        raise ValueError(f"decision must be one of {LINK_DECISIONS}")
    with _LOCK:
        data = load_decisions()
        data["links"][str(fix_pr)] = {
            "decision": decision,
            "note": note[:2000],
            "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }
        _write_json_atomic(decisions_path(), data)
        return data["links"][str(fix_pr)]


# ── reports ──────────────────────────────────────────────────────────────────


def save_attribution(report: dict) -> str:
    """Write one attribution report. Refuses to DOWNGRADE an existing one.

    Every writer funnels through here -- the nightly scan (`batch` ->
    `import-reports`) and the re-attribute route both -- so the "a re-run must
    never lose evidence" rule belongs here rather than in one caller. A run that
    names no candidate while the stored report names one is a failure of this
    environment (the clone moved on, the commit is unreachable, `gh` lost its
    auth), not a finding: saving it would delete a good report and its evidence.

    Returns the path written, or the existing path unchanged when the write was
    refused -- callers that need to tell the difference compare `culprit_pr`.
    Found by review on PR #2354.
    """
    fix_pr = int(report.get("fix_pr", 0))
    path = os.path.join(reports_dir(), f"{fix_pr}.json")

    if not (report.get("candidates") or []):
        existing = _read_json(path)
        if existing and (existing.get("candidates") or []):
            return path

    _write_json_atomic(path, report)
    return path


def import_jsonl(jsonl_path: str) -> int:
    """Split a batch JSONL into per-PR report files. Returns the count written."""
    n = 0
    with open(jsonl_path, encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(rec, dict) and rec.get("fix_pr"):
                save_attribution(rec)
                n += 1
    return n


def load_report(fix_pr: int, include_evidence: bool = True) -> dict | None:
    """Merge attribution + analysis + decisions into one report view.

    Diffs are deliberately NOT included -- they live in the bundle and would make
    a list response enormous. The UI fetches a bundle only when a human drills in.
    """
    att = _read_json(os.path.join(reports_dir(), f"{fix_pr}.json"))
    if att is None:
        return None
    # Validate the analysis HERE, not only in the CLI checker. This is the load
    # path the HTTP routes and the backlog use, so an analysis that never passed
    # `check-analysis` (hand-edited, or written by an older schema) would otherwise
    # flow into the apply prompt with a root-cause class nothing had vetted. A
    # failing analysis is DISCARDED: the attribution still renders, the pair simply
    # reads as un-analysed, which is the honest state. Found by review on PR #2354.
    ana, ana_errors = analysis.load_and_validate(
        os.path.join(analysis_dir(), f"analysis-{fix_pr}.json")
    )
    if ana_errors or not isinstance(ana, dict):
        ana = {}
    dec = load_decisions()

    cands = att.get("candidates") or []
    top = cands[0] if cands else {}

    # The analysis must agree with the attribution about WHO the culprit is.
    #
    # Matching on the filename alone was not enough: `post_reattribute` retires a
    # stale analysis, but a scan-driven re-attribution moves the culprit without
    # going through that route, and the old analysis -- still named
    # `analysis-<fix_pr>.json` -- would attach to the new attribution and describe
    # a pull request that is no longer the culprit. Every judgement in it, and
    # every proposal drawn from it, would be about the wrong PR.
    #
    # Equality is the ONLY passing case -- including `None == None`, which means
    # both sides agree there is no culprit PR (a culprit commit that predates the
    # PR workflow). An earlier version required both sides to be non-None before
    # comparing, which failed OPEN: an analysis recorded against no culprit PR
    # attached to an attribution that had since found one, and described a pull
    # request it had never seen. Found by review on PR #2354.
    if ana and ana.get("culprit_pr") != top.get("pr"):
        ana = {}
    proposals = []
    for i, prop in enumerate(ana.get("proposals") or []):
        if not isinstance(prop, dict):
            continue
        pid = proposal_id(fix_pr, i)
        proposals.append(
            {
                "id": pid,
                "bucket": prop.get("bucket"),
                "title": prop.get("title"),
                "text": prop.get("text"),
                "rationale": prop.get("rationale"),
                "confidence": prop.get("confidence"),
                "decision": (dec["proposals"].get(pid) or {}).get("decision"),
                "decision_note": (dec["proposals"].get(pid) or {}).get("note"),
                "decided_at": (dec["proposals"].get(pid) or {}).get("at"),
            }
        )

    out = {
        "fix_pr": fix_pr,
        "fix_title": att.get("fix_title"),
        "fix_url": att.get("fix_url"),
        "fix_merged_at": att.get("fix_merged_at"),
        "culprit_pr": top.get("pr"),
        "culprit_subject": top.get("subject"),
        "culprit_commits": top.get("commits") or [],
        "culprit_files_touched": top.get("largest_commit_files"),
        "verdict": att.get("verdict"),
        "confidence": att.get("confidence"),
        "flags": att.get("flags") or [],
        "signal_weight": att.get("signal_weight"),
        "analysis_present": bool(ana),
        "link_verdict": ana.get("culprit_link_verdict"),
        "link_reason": ana.get("culprit_link_reason"),
        "root_cause_class": ana.get("root_cause_class"),
        "root_cause": ana.get("root_cause"),
        "why_review_missed": ana.get("why_review_missed"),
        "why_tests_missed": ana.get("why_tests_missed"),
        "prompt_injection_observed": bool(ana.get("prompt_injection_observed")),
        "proposals": proposals,
        "human_link_decision": (dec["links"].get(str(fix_pr)) or {}).get("decision"),
        "human_link_note": (dec["links"].get(str(fix_pr)) or {}).get("note"),
    }
    if include_evidence:
        out["evidence"] = att.get("evidence") or []
        out["notes"] = att.get("notes") or []
    return out


def list_reports() -> list[dict]:
    """Summaries for the list view, newest fix PR first."""
    out: list[dict] = []
    for name in os.listdir(reports_dir()):
        if not name.endswith(".json"):
            continue
        stem = name[:-5]
        if not stem.isdigit():
            continue
        rep = load_report(int(stem), include_evidence=False)
        if rep is None:
            continue
        buckets: dict[str, int] = {}
        undecided = 0
        for prop in rep["proposals"]:
            b = str(prop.get("bucket") or "?")
            buckets[b] = buckets.get(b, 0) + 1
            if not prop.get("decision"):
                undecided += 1
        out.append(
            {
                "fix_pr": rep["fix_pr"],
                "fix_title": rep["fix_title"],
                "fix_url": rep["fix_url"],
                "fix_merged_at": rep["fix_merged_at"],
                "culprit_pr": rep["culprit_pr"],
                "culprit_subject": rep["culprit_subject"],
                "verdict": rep["verdict"],
                "confidence": rep["confidence"],
                "flags": rep["flags"],
                "link_verdict": rep["link_verdict"],
                "root_cause_class": rep["root_cause_class"],
                "analysis_present": rep["analysis_present"],
                "proposal_buckets": buckets,
                "proposals_total": len(rep["proposals"]),
                "proposals_undecided": undecided,
                "human_link_decision": rep["human_link_decision"],
            }
        )
    out.sort(key=lambda r: r["fix_pr"], reverse=True)
    return out


def load_bundle(fix_pr: int) -> dict | None:
    return _read_json(os.path.join(bundles_dir(), f"bundle-{fix_pr}.json"))


# ── state ────────────────────────────────────────────────────────────────────


def load_state() -> dict:
    st = _read_json(state_path()) or {}
    st.setdefault("schema", 1)
    st.setdefault("repos", [])
    st.setdefault("last_scan", None)
    return st


def save_state(state: dict) -> None:
    with _LOCK:
        _write_json_atomic(state_path(), state)


def touch_scan(summary: dict | None = None) -> dict:
    with _LOCK:
        st = load_state()
        st["last_scan"] = {
            "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            **(summary or {}),
        }
        _write_json_atomic(state_path(), st)
        return st["last_scan"]
